export const TAB_ITEMS = ["Visas", "Haj & Umrah", "Flights", "Hotels"];

export const TAB_CONTENT = {
  Visas: {
    type: "table",
    columns: ["clientName", "from", "destination", "departureDate", "cost"],
    data: [
      {
        clientName: "Amit Rana",
        from: "Delhi",
        destination: "Canada",
        departureDate: "30 June 2025",
        cost: "₹17,000",
      },
      {
        clientName: "Sneha Kapoor",
        from: "Mumbai",
        destination: "UK",
        departureDate: "1 July 2025",
        cost: "₹19,000",
      },
      {
        clientName: "Rohit Mehta",
        from: "Delhi",
        destination: "Germany",
        departureDate: "5 July 2025",
        cost: "₹20,500",
      },
      {
        clientName: "Neha Sharma",
        from: "Ahmedabad",
        destination: "France",
        departureDate: "10 July 2025",
        cost: "₹21,000",
      },
      {
        clientName: "Vikram Das",
        from: "Chennai",
        destination: "USA",
        departureDate: "15 July 2025",
        cost: "₹34,000",
      },
      {
        clientName: "Sania Verma",
        from: "Jaipur",
        destination: "UAE",
        departureDate: "20 July 2025",
        cost: "₹28,000",
      },
    ],
  },

  "Haj & Umrah": {
    type: "table",
    columns: [
      "fullName",
      "nationality",
      "passportNumber",
      "departureCity",
      "preferredPackage",
      "departureDate",
      "returnDate",
    ],
    data: [
      {
        fullName: "Zaid Khan",
        nationality: "Indian",
        passportNumber: "M1234567",
        departureCity: "Delhi",
        preferredPackage: "Silver",
        departureDate: "5 July 2025",
        returnDate: "20 July 2025",
      },
      {
        fullName: "Fatima Sheikh",
        nationality: "Indian",
        passportNumber: "N7654321",
        departureCity: "Mumbai",
        preferredPackage: "Gold",
        departureDate: "10 July 2025",
        returnDate: "25 July 2025",
      },
      {
        fullName: "Imran Ali",
        nationality: "Indian",
        passportNumber: "P9876543",
        departureCity: "Hyderabad",
        preferredPackage: "Platinum",
        departureDate: "15 July 2025",
        returnDate: "30 July 2025",
      },
      {
        fullName: "Sara Ansari",
        nationality: "Indian",
        passportNumber: "Q1357924",
        departureCity: "Kolkata",
        preferredPackage: "Silver",
        departureDate: "20 July 2025",
        returnDate: "5 August 2025",
      },
    ],
  },

  Flights: {
    type: "table",
    columns: ["clientName", "from", "destination", "departureDate", "cost"],
    data: [
      {
        clientName: "Rahul Sharma",
        from: "Delhi",
        destination: "Singapore",
        departureDate: "1 July 2025",
        cost: "₹22,000",
      },
      {
        clientName: "Kavita Rao",
        from: "Mumbai",
        destination: "Dubai",
        departureDate: "15 July 2025",
        cost: "₹18,500",
      },
      {
        clientName: "Ankit Verma",
        from: "Bangalore",
        destination: "London",
        departureDate: "20 July 2025",
        cost: "₹32,000",
      },
      {
        clientName: "Neha Kapoor",
        from: "Chennai",
        destination: "New York",
        departureDate: "5 Aug 2025",
        cost: "₹65,000",
      },
      {
        clientName: "Mohit Sinha",
        from: "Ahmedabad",
        destination: "Toronto",
        departureDate: "10 Aug 2025",
        cost: "₹54,000",
      },
      {
        clientName: "Sanya Bhatia",
        from: "Jaipur",
        destination: "Bangkok",
        departureDate: "18 Aug 2025",
        cost: "₹19,000",
      },
    ],
  },

  Hotels: {
    type: "table",
    columns: ["clientName", "hotel", "roomType", "stay", "cost"],
    data: [
      {
        clientName: "Shalini Mehra",
        hotel: "The Grand Paris",
        roomType: "Deluxe Suite",
        stay: "5 Aug - 10 Aug 2025",
        cost: "₹45,000",
      },
      {
        clientName: "Amit Jain",
        hotel: "Skyview Bangkok",
        roomType: "Standard Room",
        stay: "12 Aug - 17 Aug 2025",
        cost: "₹20,000",
      },
      {
        clientName: "Nikita Shah",
        hotel: "Beach Villa Goa",
        roomType: "Luxury Villa",
        stay: "1 Sept - 3 Sept 2025",
        cost: "₹9,500",
      },
      {
        clientName: "Rohit Tiwari",
        hotel: "Palm Dubai",
        roomType: "King Room",
        stay: "10 Sept - 15 Sept 2025",
        cost: "₹25,000",
      },
      {
        clientName: "Pooja Yadav",
        hotel: "Island Pearl Maldives",
        roomType: "Overwater Bungalow",
        stay: "18 Sept - 24 Sept 2025",
        cost: "₹60,000",
      },
      {
        clientName: "Alok Desai",
        hotel: "City Inn Delhi",
        roomType: "Budget Room",
        stay: "28 Sept - 30 Sept 2025",
        cost: "₹5,800",
      },
    ],
  },
};

export const MobileTabData = [
  {
    name: "Karan Joshi",
    from: "India",
    to: "Canada",
    departure: "30 June 2025",
    priority: "High",
    payment: "17,000",
    email: "karan.joshi@gmail.com",
    phone: "+91 89456123",
  },
  {
    name: "Priya Mehra",
    from: "India",
    to: "USA",
    departure: "05 July 2025",
    priority: "Low",
    payment: "25,000",
    email: "priya.mehra@gmail.com",
    phone: "+91 9876543210",
  },
  {
    name: "Amit Singh",
    from: "India",
    to: "UK",
    departure: "10 July 2025",
    priority: "High",
    payment: "30,000",
    email: "amit.singh@gmail.com",
    phone: "+91 9123456780",
  },
  {
    name: "Neha Sharma",
    from: "India",
    to: "Australia",
    departure: "15 July 2025",
    priority: "Low",
    payment: "20,000",
    email: "neha.sharma@gmail.com",
    phone: "+91 9988776655",
  },
  {
    name: "Rohit Verma",
    from: "India",
    to: "Germany",
    departure: "20 July 2025",
    priority: "High",
    payment: "22,000",
    email: "rohit.verma@gmail.com",
    phone: "+91 9090909090",
  },
  {
    name: "Sonal Kapoor",
    from: "India",
    to: "France",
    departure: "25 July 2025",
    priority: "Low",
    payment: "19,000",
    email: "sonal.kapoor@gmail.com",
    phone: "+91 9012345678",
  },
];
