"use client";
import SplashScreen from "@/commonComponents/uikit/SplashScreen";
import "./globals.scss";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-poppins",
});
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const pathname = usePathname();
  const isHome = pathname === "/" 
  const [isLoading, setIsLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, []);

  return (
    <html lang="en" className={poppins.variable}>
       {isLoading &&  (
          <SplashScreen finishLoading={() => setIsLoading(false)} />
        ) }
      <body>{children}</body>
    </html>
  );
}
