# .github/workflows/node.js.yml
name: Deploy to VPS via Webhook

on:
  push:
    branches:
      - development

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Call VPS Webhook
      run: |
        PAYLOAD='{"ref":"refs/heads/development"}'
        SIGNATURE="sha256=$(echo -n $PAYLOAD | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | sed 's/^.* //')"

        curl -X POST \
          --fail \                # ⬅️ ye add karo
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: $SIGNATURE" \
          --data "$PAYLOAD" \
          http://69.62.75.137:9000/webhook
